version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:

  servicea:
    build:
      context: services/service
    environment:
      PORT: ":8081"
      CONTENT: "<h1>Service A</h1>"
    networks:
      - kong-net
    ports:
      - 8081:8081

  serviceb:
    build:
      context: services/service
    environment:
      PORT: ":8082"
      CONTENT: "<h1>Service b</h1>"
    networks:
      - kong-net
    ports:
      - 8082:8082

  servicec1:
    build:
      context: services/service
    environment:
      PORT: ":8083"
      CONTENT: "<h1>Service C1</h1>"
    networks:
      - kong-net
    ports:
      - 8083:8083

  servicec2:
    build:
      context: services/service
    environment:
      PORT: ":7083"
      CONTENT: "<h1>Service C2</h1>"
    networks:
      - kong-net
    ports:
      - 7083:7083